### ISSUE TITLE
cavity simulation ... a new torchio transform

### ISSUE THREAD

**Issue by romainVala** [fepegar/resector#7]
**🚀 Feature**

I have seen this amazing paper, from an author I know !
[ Pérez-García et al., 2021, An unsupervised learning strategy for postoperative brain cavity segmentation simulating resections during training - International Journal of Computer Assisted Radiology and Surgery (IJCARS).](https://link.springer.com/article/10.1007%2Fs11548-021-02420-2)

You do  use of torchio, but the simulation of cavity was not a torchio transform, but this package
[resector](https://github.com/fepegar/resector)

**Motivation**

For anomalie detection, or tumor detection, I think this kind of transform is a good start.
may be for the tumor, one would like more control on the texture  to replace the good tissue
but adding just noise (or csf value) is a good start

**Pitch**

I did not look more closely, ... is there any difficulty, to make it a torchio transform ?

**Alternatives**

**Additional context**

**Comment by romainVala** [comment]
ok, I could test it, 
but I thing it would be nice to have it directly on torchio ...
(although may be not a priority)

thanks

**Comment by fepegar** [comment]
The code of `resector` is not ready to be part of TorchIO. It is messier and untested as it was used for quick prototyping during a research project. Moreover, from my point of view, it is a very specific application that doesn't really have a place in a more general medical image processing library. Given that it can be easily installed using `pip`, it should be trivial to use both libraries together.
