### ISSUE TITLE
Resector Error in Terminal

### ISSUE THREAD

**Issue by roryjpiper** [fepegar/resector#8]
I've typed in `resect -help` and have the following output. Anyone else had this issue?

```python-traceback
rorypiper@MS00048528 anat % resect sub-15_preop_t1w_iso1mm.nii.gz gif_parcellation.nii.gz t1_resected.nii.gz t1_resection_label.nii.gz
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (SimpleITK 2.0.2 (/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages), Requirement.parse('SimpleITK!=2.0.*'), {'torchio'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/bin/resect", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3251, in <module>
    def _initialize_master_working_set():
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3234, in _call_aside
    f(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3263, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pkg_resources/__init__.py", line 585, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pkg_resources/__init__.py", line 598, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (SimpleITK 2.0.2 (/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages), Requirement.parse('SimpleITK!=2.0.*'), {'torchio'})
```

**Comment by fepegar** [comment]
Hi, @roryjpiper. I incorrectly pointed you to the TorchIO repo, so I moved the issue here instead.

I suspect some of your installed libraries are clashing. I have updated the installation instructions on the README of this repository. Things should be easier now. Please try them and let me know if that worked.

This code is a bit experimental and not very well documented, so feel free to request features, ask questions and report any other issues that you have. I'm also happy to meet if you think the library can be further adapted to your needs.

**Comment by roryjpiper** [comment]
Thanks Fernando,

Thanks very much for this. I have uninstalled everything and then tried to re-install using the read-me from GitHub …..unfortunately, I am still getting the glitch below.

I would be very grateful if we could meet - virtual or in-person - to troubleshoot.

Thanks,
Rory

***@***.*** sub-001 % resect sub-001_preop_T1w.nii.gz gif_parcellation.nii.gz t1_resected.nii.gz t1_resection_label.nii.gz
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/bin/resect", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3251, in <module>
    def _initialize_master_working_set():
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3234, in _call_aside
    f(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3263, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'resector' distribution was not found and is required by the application

**Comment by fepegar** [comment]
Could you please paste here the exact commands you are using?

**Comment by roryjpiper** [comment]
Hi,

This what I typed

resect sub-001_preop_T1w.nii.gz gif_parcellation.nii.gz t1_resected.nii.gz t1_resection_label.nii.gz

**Comment by fepegar** [comment]
I meant all the commands you used to install the library as well, not just to run the algorithm, sorry.

**Comment by roryjpiper** [comment]
Thanks.

Here it is. Line by line. I have seen the small error at the start about the conda directory. Is this the whole problem?


***@***.*** ~ % conda create --name resenv python=3.8 --yes && conda activate resenv
Collecting package metadata (current_repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.10.1
  latest version: 4.10.3

Please update conda by running

    $ conda update -n base -c defaults conda



## Package Plan ##

  environment location: /Users/rorypiper/opt/anaconda3/envs/resenv

  added / updated specs:
    - python=3.8


The following NEW packages will be INSTALLED:

  ca-certificates    pkgs/main/osx-64::ca-certificates-2021.7.5-hecd8cb5_1
  certifi            pkgs/main/osx-64::certifi-2021.5.30-py38hecd8cb5_0
  libcxx             pkgs/main/osx-64::libcxx-10.0.0-1
  libffi             pkgs/main/osx-64::libffi-3.3-hb1e8313_2
  ncurses            pkgs/main/osx-64::ncurses-6.2-h0a44026_1
  openssl            pkgs/main/osx-64::openssl-1.1.1k-h9ed2024_0
  pip                pkgs/main/osx-64::pip-21.2.2-py38hecd8cb5_0
  python             pkgs/main/osx-64::python-3.8.11-h88f2d9e_0_cpython
  readline           pkgs/main/osx-64::readline-8.1-h9ed2024_0
  setuptools         pkgs/main/osx-64::setuptools-52.0.0-py38hecd8cb5_0
  sqlite             pkgs/main/osx-64::sqlite-3.36.0-hce871da_0
  tk                 pkgs/main/osx-64::tk-8.6.10-hb0a8c7a_0
  wheel              pkgs/main/noarch::wheel-0.36.2-pyhd3eb1b0_0
  xz                 pkgs/main/osx-64::xz-5.2.5-h1de35cc_0
  zlib               pkgs/main/osx-64::zlib-1.2.11-h1de35cc_3


Preparing transaction: done
Verifying transaction: - WARNING conda.core.path_actions:verify(962): Unable to create environments file. Path not writable.
  environment location: /Users/rorypiper/.conda/environments.txt

done
Executing transaction: / WARNING conda.core.envs_manager:register_env(50): Unable to register environment. Path not writable or missing.
  environment location: /Users/rorypiper/opt/anaconda3/envs/resenv
  registry file: /Users/rorypiper/.conda/environments.txt
done
#
# To activate this environment, use
#
#     $ conda activate resenv
#
# To deactivate an active environment, use
#
#     $ conda deactivate

(resenv) ***@***.*** ~ % pip install light-the-torch
Collecting light-the-torch
  Using cached light_the_torch-0.3.3-py3-none-any.whl (18 kB)
Collecting pip<20.3.*,>=20.1.*
  Using cached pip-20.2.4-py2.py3-none-any.whl (1.5 MB)
Installing collected packages: pip, light-the-torch
  Attempting uninstall: pip
    Found existing installation: pip 21.2.2
    Uninstalling pip-21.2.2:
      Successfully uninstalled pip-21.2.2
Successfully installed light-the-torch-0.3.3 pip-20.2.4
(resenv) ***@***.*** ~ % ltt install torch
Collecting torch==1.9.0
  Using cached https://download.pytorch.org/whl/cpu/torch-1.9.0-cp38-none-macosx_10_9_x86_64.whl (127.9 MB)
Collecting typing-extensions
  Using cached typing_extensions-3.10.0.0-py3-none-any.whl (26 kB)
Installing collected packages: typing-extensions, torch
Successfully installed torch-1.9.0 typing-extensions-3.10.0.0
WARNING: You are using pip version 20.2.4; however, version 21.2.2 is available.
You should consider upgrading via the '/Users/rorypiper/opt/anaconda3/envs/resenv/bin/python -m pip install --upgrade pip' command.
Requirement already satisfied: torch in ./opt/anaconda3/envs/resenv/lib/python3.8/site-packages (1.9.0)
Requirement already satisfied: typing-extensions in ./opt/anaconda3/envs/resenv/lib/python3.8/site-packages (from torch) (3.10.0.0)
WARNING: You are using pip version 20.2.4; however, version 21.2.2 is available.
You should consider upgrading via the '/Users/rorypiper/opt/anaconda3/envs/resenv/bin/python -m pip install --upgrade pip' command.
(resenv) ***@***.*** ~ % pip install git+https://github.com/fepegar/resector
Collecting git+https://github.com/fepegar/resector
  Cloning https://github.com/fepegar/resector to /private/var/folders/2p/vgnsmsgj4vl20d8gff9z74ch0000gp/T/pip-req-build-y6fplz6a
Collecting Click>=7.0
  Using cached click-8.0.1-py3-none-any.whl (97 kB)
Processing ./Library/Caches/pip/wheels/b3/e1/a8/cf0ce54c603bc4e4965e354a7aa3d8dacb8714f2c2db82ba04/noise-1.2.2-cp38-cp38-macosx_10_9_x86_64.whl
Collecting torchio
  Downloading torchio-0.18.46-py2.py3-none-any.whl (148 kB)
     |████████████████████████████████| 148 kB 11.6 MB/s 
Collecting SimpleITK
  Using cached SimpleITK-2.1.0-cp38-cp38-macosx_10_9_x86_64.whl (44.3 MB)
Collecting scikit-image
  Using cached scikit_image-0.18.2-cp38-cp38-macosx_10_9_x86_64.whl (12.8 MB)
Collecting scipy
  Using cached scipy-1.7.1-cp38-cp38-macosx_10_9_x86_64.whl (32.6 MB)
Collecting vtk
  Using cached vtk-9.0.3-cp38-cp38-macosx_10_10_x86_64.whl (47.9 MB)
Collecting numpy>=1.15
  Using cached numpy-1.21.1-cp38-cp38-macosx_10_9_x86_64.whl (16.9 MB)
Collecting tqdm
  Using cached tqdm-4.62.0-py2.py3-none-any.whl (76 kB)
Collecting nibabel
  Using cached nibabel-3.2.1-py3-none-any.whl (3.3 MB)
Requirement already satisfied: torch>=1.1 in ./opt/anaconda3/envs/resenv/lib/python3.8/site-packages (from torchio->resector==0.2.9) (1.9.0)
Collecting humanize
  Using cached humanize-3.11.0-py3-none-any.whl (90 kB)
Collecting Deprecated
  Using cached Deprecated-1.2.12-py2.py3-none-any.whl (9.5 kB)
Collecting pillow!=7.1.0,!=7.1.1,>=4.3.0
  Using cached Pillow-8.3.1-cp38-cp38-macosx_10_10_x86_64.whl (2.9 MB)
Collecting PyWavelets>=1.1.1
  Using cached PyWavelets-1.1.1-cp38-cp38-macosx_10_9_x86_64.whl (4.3 MB)
Collecting tifffile>=2019.7.26
  Using cached tifffile-2021.7.30-py3-none-any.whl (171 kB)
Collecting matplotlib!=3.0.0,>=2.0.0
  Using cached matplotlib-3.4.2-cp38-cp38-macosx_10_9_x86_64.whl (7.2 MB)
Collecting imageio>=2.3.0
  Using cached imageio-2.9.0-py3-none-any.whl (3.3 MB)
Collecting networkx>=2.0
  Using cached networkx-2.6.2-py3-none-any.whl (1.9 MB)
Collecting autobahn>=17.7.1
  Using cached autobahn-21.3.1-py2.py3-none-any.whl (495 kB)
Collecting Twisted>=17.5.0
  Using cached Twisted-21.7.0-py3-none-any.whl (3.1 MB)
Collecting wslink>=0.1.3
  Using cached wslink-0.2.0-py2.py3-none-any.whl (19 kB)
Collecting packaging>=14.3
  Using cached packaging-21.0-py3-none-any.whl (40 kB)
Requirement already satisfied: typing-extensions in ./opt/anaconda3/envs/resenv/lib/python3.8/site-packages (from torch>=1.1->torchio->resector==0.2.9) (3.10.0.0)
Requirement already satisfied: setuptools in ./opt/anaconda3/envs/resenv/lib/python3.8/site-packages (from humanize->torchio->resector==0.2.9) (52.0.0.post20210125)
Processing ./Library/Caches/pip/wheels/5f/fd/9e/b6cf5890494cb8ef0b5eaff72e5d55a70fb56316007d6dfe73/wrapt-1.12.1-cp38-cp38-macosx_10_9_x86_64.whl
Collecting cycler>=0.10
  Using cached cycler-0.10.0-py2.py3-none-any.whl (6.5 kB)
Collecting python-dateutil>=2.7
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting kiwisolver>=1.0.1
  Using cached kiwisolver-1.3.1-cp38-cp38-macosx_10_9_x86_64.whl (61 kB)
Collecting pyparsing>=2.2.1
  Using cached pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
Collecting hyperlink>=21.0.0
  Using cached hyperlink-21.0.0-py2.py3-none-any.whl (74 kB)
Collecting txaio>=21.2.1
  Using cached txaio-21.2.1-py2.py3-none-any.whl (30 kB)
Collecting cryptography>=3.4.6
  Using cached cryptography-3.4.7-cp36-abi3-macosx_10_10_x86_64.whl (2.0 MB)
Collecting constantly>=15.1
  Using cached constantly-15.1.0-py2.py3-none-any.whl (7.9 kB)
Collecting attrs>=19.2.0
  Using cached attrs-21.2.0-py2.py3-none-any.whl (53 kB)
Collecting zope.interface>=4.4.2
  Using cached zope.interface-5.4.0-cp38-cp38-macosx_10_14_x86_64.whl (208 kB)
Collecting incremental>=21.3.0
  Using cached incremental-21.3.0-py2.py3-none-any.whl (15 kB)
Collecting Automat>=0.8.0
  Using cached Automat-20.2.0-py2.py3-none-any.whl (31 kB)
Collecting six
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting idna>=2.5
  Using cached idna-3.2-py3-none-any.whl (59 kB)
Collecting cffi>=1.12
  Using cached cffi-1.14.6-cp38-cp38-macosx_10_9_x86_64.whl (176 kB)
Collecting pycparser
  Using cached pycparser-2.20-py2.py3-none-any.whl (112 kB)
Building wheels for collected packages: resector
  Building wheel for resector (setup.py) ... done
  Created wheel for resector: filename=resector-0.2.9-py2.py3-none-any.whl size=86327 sha256=ff87af2895cd7046c5a26aae13a02cea444ba6aa08ff3eca1d1a17f964bd942d
  Stored in directory: /private/var/folders/2p/vgnsmsgj4vl20d8gff9z74ch0000gp/T/pip-ephem-wheel-cache-xd7ryi_t/wheels/9a/ed/b3/79d655777b74420c62515cca24d1af82c33994055c9947f4a5
Successfully built resector
Installing collected packages: Click, noise, numpy, tqdm, SimpleITK, pyparsing, packaging, nibabel, humanize, scipy, wrapt, Deprecated, torchio, pillow, PyWavelets, tifffile, six, cycler, python-dateutil, kiwisolver, matplotlib, imageio, networkx, scikit-image, idna, hyperlink, txaio, pycparser, cffi, cryptography, autobahn, constantly, attrs, zope.interface, incremental, Automat, Twisted, wslink, vtk, resector

Successfully installed Automat-20.2.0 Click-8.0.1 Deprecated-1.2.12 PyWavelets-1.1.1 SimpleITK-2.1.0 Twisted-21.7.0 attrs-21.2.0 autobahn-21.3.1 cffi-1.14.6 constantly-15.1.0 cryptography-3.4.7 cycler-0.10.0 humanize-3.11.0 hyperlink-21.0.0 idna-3.2 imageio-2.9.0 incremental-21.3.0 kiwisolver-1.3.1 matplotlib-3.4.2 networkx-2.6.2 nibabel-3.2.1 noise-1.2.2 numpy-1.21.1 packaging-21.0 pillow-8.3.1 pycparser-2.20 pyparsing-2.4.7 python-dateutil-2.8.2 resector-0.2.9 scikit-image-0.18.2 scipy-1.7.1 six-1.16.0 tifffile-2021.7.30 torchio-0.18.46 tqdm-4.62.0 txaio-21.2.1 vtk-9.0.3 wrapt-1.12.1 wslink-0.2.0 zope.interface-5.4.0
WARNING: You are using pip version 20.2.4; however, version 21.2.2 is available.
You should consider upgrading via the '/Users/rorypiper/opt/anaconda3/envs/resenv/bin/python -m pip install --upgrade pip' command.
r%                                                                                                                    (resenv) ***@***.*** ~ % 
(resenv) ***@***.*** ~ % resect --help
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/bin/resect", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3251, in <module>
    def _initialize_master_working_set():
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3234, in _call_aside
    f(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3263, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'resector' distribution was not found and is required by the application
(resenv) ***@***.*** ~ %

**Comment by fepegar** [comment]
> I have seen the small error at the start about the conda directory. Is this the whole problem?

It might be. What is the output of `which resector`?

I recommend deleting the environment with `conda remove --all --name resenv`, then trying [this solution](https://stackoverflow.com/a/59842072/3956024) and start over.

**Comment by roryjpiper** [comment]
Thanks. That has helped the first error ….but still getting the same end result:

***@***.*** bin % resect --help
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/bin/resect", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3251, in <module>
    def _initialize_master_working_set():
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3234, in _call_aside
    f(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3263, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'resector' distribution was not found and is required by the application
***@***.*** bin %

**Comment by fepegar** [comment]
`/Library/Frameworks/Python.framework/Versions/3.8/bin`

It seems that your computer is trying to use the system Python, not the `conda` one. What is the output of `which python`?

**Comment by fepegar** [comment]
And `which pip`.

**Comment by fepegar** [comment]
And `which resect`.
